name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        cc -o nobuild nobuild.c
        ./nobuild
      working-directory: . 

    - name: Test
      run: |
        python3 run_tests.py
      working-directory: . 
